# GNU Make project makefile autogenerated by Premake
ifndef config
  config=release32
endif

ifndef verbose
  SILENT = @
endif

ifndef CC
  CC = gcc
endif

ifndef CXX
  CXX = g++
endif

ifndef AR
  AR = ar
endif

ifeq ($(config),release32)
  OBJDIR     = obj/x32/Release
  TARGETDIR  = ../../basety
  TARGET     = $(TARGETDIR)/gamearm.so
  DEFINES   += -DNDEBUG -D__DOOM__ -DGAME_DLL
  INCLUDES  += -I../idlib
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O3 -Wall -fPIC -pipe -Wall -Wno-unknown-pragmas -fvisibility=hidden -fno-strict-aliasing -Wno-unused-variable -ffast-math -fno-unsafe-math-optimizations -fomit-frame-pointer
  CFLAGS    += -mcpu=cortex-a8 -mfloat-abi=softfp -mfpu=neon -fpic -fno-short-enums -ffunction-sections -funwind-tables -fstack-protector -ftree-vectorize -fsingle-precision-constant
  CFLAGS    += -I$(NDK)/platforms/android-4/arch-arm/usr/include -D__MATH_NEON -DANDROID #-D__linux__
  CFLAGS    += -I$(NDK)/prebuilt/windows/lib/gcc/arm-linux-androideabi/4.4.3/include
  CXXFLAGS  += $(CFLAGS)
  CXXFLAGS  += -I$(NDK)/sources/cxx-stl/stlport/stlport
  #LDFLAGS   += -s -shared -m32 -L/usr/lib32
  LDFLAGS   += -nostdlib -shared -L$(NDK)/platforms/android-4/arch-arm/usr/lib
  LIBS      += 
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debug32)
  OBJDIR     = obj/x32/Debug
  TARGETDIR  = ../../basety
  TARGET     = $(TARGETDIR)/gamex86.so
  DEFINES   += -D_DEBUG -D__DOOM__ -DGAME_DLL
  INCLUDES  += -I../idlib
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -Wall -m32 -fPIC -pipe -Wall -Wno-unknown-pragmas -fvisibility=hidden -fno-strict-aliasing -Wno-unused-variable
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -shared -m32 -L/usr/lib32
  LIBS      += 
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release64)
  OBJDIR     = obj/x64/Release
  TARGETDIR  = ../../basety
  TARGET     = $(TARGETDIR)/gamex86_64.so
  DEFINES   += -DNDEBUG -D__DOOM__ -DGAME_DLL
  INCLUDES  += -I../idlib
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O3 -Wall -m64 -fPIC -pipe -Wall -Wno-unknown-pragmas -fvisibility=hidden -fno-strict-aliasing -Wno-unused-variable -ffast-math -fno-unsafe-math-optimizations -fomit-frame-pointer
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s -shared -m64 -L/usr/lib64
  LIBS      += 
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debug64)
  OBJDIR     = obj/x64/Debug
  TARGETDIR  = ../../basety
  TARGET     = $(TARGETDIR)/gamex86_64.so
  DEFINES   += -D_DEBUG -D__DOOM__ -DGAME_DLL
  INCLUDES  += -I../idlib
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -Wall -m64 -fPIC -pipe -Wall -Wno-unknown-pragmas -fvisibility=hidden -fno-strict-aliasing -Wno-unused-variable
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -shared -m64 -L/usr/lib64
  LIBS      += 
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
	$(OBJDIR)/Base64.o \
	$(OBJDIR)/BitMsg.o \
	$(OBJDIR)/CmdArgs.o \
	$(OBJDIR)/Dict.o \
	$(OBJDIR)/Heap.o \
	$(OBJDIR)/LangDict.o \
	$(OBJDIR)/Lexer.o \
	$(OBJDIR)/Lib.o \
	$(OBJDIR)/MapFile.o \
	$(OBJDIR)/Parser.o \
	$(OBJDIR)/precompiled.o \
	$(OBJDIR)/Str.o \
	$(OBJDIR)/Timer.o \
	$(OBJDIR)/Token.o \
	$(OBJDIR)/Bounds.o \
	$(OBJDIR)/Box.o \
	$(OBJDIR)/Frustum.o \
	$(OBJDIR)/Sphere.o \
	$(OBJDIR)/HashIndex.o \
	$(OBJDIR)/DrawVert.o \
	$(OBJDIR)/JointTransform.o \
	$(OBJDIR)/Surface.o \
	$(OBJDIR)/Surface_Patch.o \
	$(OBJDIR)/Surface_Polytope.o \
	$(OBJDIR)/Surface_SweptSpline.o \
	$(OBJDIR)/TraceModel.o \
	$(OBJDIR)/Winding.o \
	$(OBJDIR)/Winding2D.o \
	$(OBJDIR)/CRC32.o \
	$(OBJDIR)/MD4.o \
	$(OBJDIR)/MD5.o \
	$(OBJDIR)/Angles.o \
	$(OBJDIR)/Complex.o \
	$(OBJDIR)/Lcp.o \
	$(OBJDIR)/Math.o \
	$(OBJDIR)/Matrix.o \
	$(OBJDIR)/Ode.o \
	$(OBJDIR)/Plane.o \
	$(OBJDIR)/Pluecker.o \
	$(OBJDIR)/Polynomial.o \
	$(OBJDIR)/Quat.o \
	$(OBJDIR)/Rotation.o \
	$(OBJDIR)/Simd.o \
	$(OBJDIR)/Simd_3DNow.o \
	$(OBJDIR)/Simd_Generic.o \
	$(OBJDIR)/Simd_MMX.o \
	$(OBJDIR)/Simd_SSE.o \
	$(OBJDIR)/Simd_SSE2.o \
	$(OBJDIR)/Simd_SSE3.o \
	$(OBJDIR)/Vector.o \
	$(OBJDIR)/Actor.o \
	$(OBJDIR)/AF.o \
	$(OBJDIR)/AFEntity.o \
	$(OBJDIR)/BrittleFracture.o \
	$(OBJDIR)/Camera.o \
	$(OBJDIR)/Entity.o \
	$(OBJDIR)/Fx.o \
	$(OBJDIR)/GameEdit.o \
	$(OBJDIR)/Game_local.o \
	$(OBJDIR)/Game_network.o \
	$(OBJDIR)/IK.o \
	$(OBJDIR)/Item.o \
	$(OBJDIR)/Light.o \
	$(OBJDIR)/Misc.o \
	$(OBJDIR)/Moveable.o \
	$(OBJDIR)/Mover.o \
	$(OBJDIR)/MultiplayerGame.o \
	$(OBJDIR)/Player.o \
	$(OBJDIR)/PlayerIcon.o \
	$(OBJDIR)/PlayerView.o \
	$(OBJDIR)/Projectile.o \
	$(OBJDIR)/Pvs.o \
	$(OBJDIR)/SecurityCamera.o \
	$(OBJDIR)/SmokeParticles.o \
	$(OBJDIR)/Sound.o \
	$(OBJDIR)/Target.o \
	$(OBJDIR)/Trigger.o \
	$(OBJDIR)/Weapon.o \
	$(OBJDIR)/WorldSpawn.o \
	$(OBJDIR)/AAS.o \
	$(OBJDIR)/AAS_debug.o \
	$(OBJDIR)/AAS_pathing.o \
	$(OBJDIR)/AAS_routing.o \
	$(OBJDIR)/AI.o \
	$(OBJDIR)/AI_events.o \
	$(OBJDIR)/AI_pathing.o \
	$(OBJDIR)/AI_Vagary.o \
	$(OBJDIR)/Anim.o \
	$(OBJDIR)/Anim_Blend.o \
	$(OBJDIR)/Anim_Import.o \
	$(OBJDIR)/Anim_Testmodel.o \
	$(OBJDIR)/Class.o \
	$(OBJDIR)/DebugGraph.o \
	$(OBJDIR)/Event.o \
	$(OBJDIR)/SaveGame.o \
	$(OBJDIR)/SysCmds.o \
	$(OBJDIR)/SysCvar.o \
	$(OBJDIR)/TypeInfo.o \
	$(OBJDIR)/Clip.o \
	$(OBJDIR)/Force.o \
	$(OBJDIR)/Force_Constant.o \
	$(OBJDIR)/Force_Drag.o \
	$(OBJDIR)/Force_Field.o \
	$(OBJDIR)/Force_Spring.o \
	$(OBJDIR)/Physics.o \
	$(OBJDIR)/Physics_Actor.o \
	$(OBJDIR)/Physics_AF.o \
	$(OBJDIR)/Physics_Base.o \
	$(OBJDIR)/Physics_Monster.o \
	$(OBJDIR)/Physics_Parametric.o \
	$(OBJDIR)/Physics_Player.o \
	$(OBJDIR)/Physics_RigidBody.o \
	$(OBJDIR)/Physics_Static.o \
	$(OBJDIR)/Physics_StaticMulti.o \
	$(OBJDIR)/Push.o \
	$(OBJDIR)/Script_Compiler.o \
	$(OBJDIR)/Script_Interpreter.o \
	$(OBJDIR)/Script_Program.o \
	$(OBJDIR)/Script_Thread.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking game
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning game
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
	-$(SILENT) cp $< $(OBJDIR)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
endif

$(OBJDIR)/Base64.o: ../idlib/Base64.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/BitMsg.o: ../idlib/BitMsg.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/CmdArgs.o: ../idlib/CmdArgs.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Dict.o: ../idlib/Dict.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Heap.o: ../idlib/Heap.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LangDict.o: ../idlib/LangDict.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Lexer.o: ../idlib/Lexer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Lib.o: ../idlib/Lib.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MapFile.o: ../idlib/MapFile.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Parser.o: ../idlib/Parser.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/precompiled.o: ../idlib/precompiled.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Str.o: ../idlib/Str.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Timer.o: ../idlib/Timer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Token.o: ../idlib/Token.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Bounds.o: ../idlib/bv/Bounds.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Box.o: ../idlib/bv/Box.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Frustum.o: ../idlib/bv/Frustum.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Sphere.o: ../idlib/bv/Sphere.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/HashIndex.o: ../idlib/containers/HashIndex.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawVert.o: ../idlib/geometry/DrawVert.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JointTransform.o: ../idlib/geometry/JointTransform.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Surface.o: ../idlib/geometry/Surface.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Surface_Patch.o: ../idlib/geometry/Surface_Patch.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Surface_Polytope.o: ../idlib/geometry/Surface_Polytope.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Surface_SweptSpline.o: ../idlib/geometry/Surface_SweptSpline.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/TraceModel.o: ../idlib/geometry/TraceModel.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Winding.o: ../idlib/geometry/Winding.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Winding2D.o: ../idlib/geometry/Winding2D.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/CRC32.o: ../idlib/hashing/CRC32.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MD4.o: ../idlib/hashing/MD4.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MD5.o: ../idlib/hashing/MD5.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Angles.o: ../idlib/math/Angles.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Complex.o: ../idlib/math/Complex.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Lcp.o: ../idlib/math/Lcp.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Math.o: ../idlib/math/Math.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Matrix.o: ../idlib/math/Matrix.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Ode.o: ../idlib/math/Ode.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Plane.o: ../idlib/math/Plane.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Pluecker.o: ../idlib/math/Pluecker.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Polynomial.o: ../idlib/math/Polynomial.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Quat.o: ../idlib/math/Quat.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Rotation.o: ../idlib/math/Rotation.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Simd.o: ../idlib/math/Simd.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Simd_3DNow.o: ../idlib/math/Simd_3DNow.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Simd_Generic.o: ../idlib/math/Simd_Generic.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Simd_MMX.o: ../idlib/math/Simd_MMX.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Simd_SSE.o: ../idlib/math/Simd_SSE.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Simd_SSE2.o: ../idlib/math/Simd_SSE2.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Simd_SSE3.o: ../idlib/math/Simd_SSE3.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Vector.o: ../idlib/math/Vector.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Actor.o: Actor.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AF.o: AF.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AFEntity.o: AFEntity.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/BrittleFracture.o: BrittleFracture.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Camera.o: Camera.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Entity.o: Entity.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Fx.o: Fx.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/GameEdit.o: GameEdit.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Game_local.o: Game_local.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Game_network.o: Game_network.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/IK.o: IK.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Item.o: Item.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Light.o: Light.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Misc.o: Misc.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Moveable.o: Moveable.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Mover.o: Mover.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MultiplayerGame.o: MultiplayerGame.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Player.o: Player.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PlayerIcon.o: PlayerIcon.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PlayerView.o: PlayerView.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Projectile.o: Projectile.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Pvs.o: Pvs.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SecurityCamera.o: SecurityCamera.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SmokeParticles.o: SmokeParticles.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Sound.o: Sound.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Target.o: Target.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Trigger.o: Trigger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Weapon.o: Weapon.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/WorldSpawn.o: WorldSpawn.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AAS.o: ai/AAS.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AAS_debug.o: ai/AAS_debug.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AAS_pathing.o: ai/AAS_pathing.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AAS_routing.o: ai/AAS_routing.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AI.o: ai/AI.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AI_events.o: ai/AI_events.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AI_pathing.o: ai/AI_pathing.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AI_Vagary.o: ai/AI_Vagary.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Anim.o: anim/Anim.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Anim_Blend.o: anim/Anim_Blend.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Anim_Import.o: anim/Anim_Import.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Anim_Testmodel.o: anim/Anim_Testmodel.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Class.o: gamesys/Class.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DebugGraph.o: gamesys/DebugGraph.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Event.o: gamesys/Event.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SaveGame.o: gamesys/SaveGame.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SysCmds.o: gamesys/SysCmds.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SysCvar.o: gamesys/SysCvar.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/TypeInfo.o: gamesys/TypeInfo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Clip.o: physics/Clip.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Force.o: physics/Force.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Force_Constant.o: physics/Force_Constant.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Force_Drag.o: physics/Force_Drag.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Force_Field.o: physics/Force_Field.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Force_Spring.o: physics/Force_Spring.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Physics.o: physics/Physics.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Physics_Actor.o: physics/Physics_Actor.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Physics_AF.o: physics/Physics_AF.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Physics_Base.o: physics/Physics_Base.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Physics_Monster.o: physics/Physics_Monster.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Physics_Parametric.o: physics/Physics_Parametric.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Physics_Player.o: physics/Physics_Player.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Physics_RigidBody.o: physics/Physics_RigidBody.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Physics_Static.o: physics/Physics_Static.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Physics_StaticMulti.o: physics/Physics_StaticMulti.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Push.o: physics/Push.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Script_Compiler.o: script/Script_Compiler.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Script_Interpreter.o: script/Script_Interpreter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Script_Program.o: script/Script_Program.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Script_Thread.o: script/Script_Thread.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"

-include $(OBJECTS:%.o=%.d)
