# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=release32
endif
export config

CC = ${NDK}/toolchains/arm-linux-androideabi-4.4.3/prebuilt/windows/bin/arm-linux-androideabi-gcc
CXX = ${NDK}/toolchains/arm-linux-androideabi-4.4.3/prebuilt/windows/bin/arm-linux-androideabi-gcc
AR = ${NDK}/toolchains/arm-linux-androideabi-4.4.3/prebuilt/windows/bin/arm-linux-androideabi-ar

export CC
export CXX
export AR

PROJECTS := idlib game #Techyon

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

idlib: 
	@echo "==== Building idlib ($(config)) ===="
	@${MAKE} --no-print-directory -C idlib -f Makefile.Android.mk

Techyon: idlib
	@echo "==== Building Techyon ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f Makefile.Android.mk

game: 
	@echo "==== Building game ($(config)) ===="
	@${MAKE} --no-print-directory -C game -f Makefile.Android.mk

clean:
	@${MAKE} --no-print-directory -C idlib -f Makefile.Android.mk clean
	@${MAKE} --no-print-directory -C . -f Techyon.make.Android.mk clean
	@${MAKE} --no-print-directory -C game -f Makefile.Android.mk clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   release32"
	@echo "   debug32"
	@echo "   release64"
	@echo "   debug64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   idlib"
	@echo "   Techyon"
	@echo "   game"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
