# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=release32
endif
export config

PROJECTS := idlib #Techyon game

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

idlib: 
	@echo "==== Building idlib ($(config)) ===="
	@${MAKE} --no-print-directory -C idlib -f Makefile.Android.mk

Techyon: idlib
	@echo "==== Building Techyon ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f Makefile.Android.mk

game: 
	@echo "==== Building game ($(config)) ===="
	@${MAKE} --no-print-directory -C game -f Makefile

clean:
	@${MAKE} --no-print-directory -C idlib -f Makefile clean
	@${MAKE} --no-print-directory -C . -f Techyon.make clean
	@${MAKE} --no-print-directory -C game -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   release32"
	@echo "   debug32"
	@echo "   release64"
	@echo "   debug64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   idlib"
	@echo "   Techyon"
	@echo "   game"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
