/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_robertbeckebans_tekuum_TekuumJNI */

#ifndef _Included_com_robertbeckebans_tekuum_TekuumJNI
#define _Included_com_robertbeckebans_tekuum_TekuumJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_robertbeckebans_tekuum_TekuumJNI
 * Method:    enableAudio
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_robertbeckebans_tekuum_TekuumJNI_enableAudio
( JNIEnv*, jclass, jboolean );

/*
 * Class:     com_robertbeckebans_tekuum_TekuumJNI
 * Method:    enableBenchmark
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_robertbeckebans_tekuum_TekuumJNI_enableBenchmark
( JNIEnv*, jclass, jboolean );

/*
 * Class:     com_robertbeckebans_tekuum_TekuumJNI
 * Method:    enableLightmaps
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_robertbeckebans_tekuum_TekuumJNI_enableLightmaps
( JNIEnv*, jclass, jboolean );

/*
 * Class:     com_robertbeckebans_tekuum_TekuumJNI
 * Method:    setGame
 * Signature: (Lcom/robertbeckebans/tekuum/Game;)V
 */
JNIEXPORT void JNICALL Java_com_robertbeckebans_tekuum_TekuumJNI_setGame
( JNIEnv*, jclass, jobject );

/*
 * Class:     com_robertbeckebans_tekuum_TekuumJNI
 * Method:    setRenderer
 * Signature: (Lcom/robertbeckebans/tekuum/TekuumRenderer;)V
 */
JNIEXPORT void JNICALL Java_com_robertbeckebans_tekuum_TekuumJNI_setRenderer
( JNIEnv*, jclass, jobject );

/*
 * Class:     com_robertbeckebans_tekuum_TekuumJNI
 * Method:    setView
 * Signature: (Lcom/robertbeckebans/tekuum/TekuumView;)V
 */
JNIEXPORT void JNICALL Java_com_robertbeckebans_tekuum_TekuumJNI_setView
( JNIEnv*, jclass, jobject );

/*
 * Class:     com_robertbeckebans_tekuum_TekuumJNI
 * Method:    showFramerate
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_robertbeckebans_tekuum_TekuumJNI_showFramerate
( JNIEnv*, jclass, jboolean );

/*
 * Class:     com_robertbeckebans_tekuum_TekuumJNI
 * Method:    initGame
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_robertbeckebans_tekuum_TekuumJNI_initGame
( JNIEnv*, jclass, jint, jint );

/*
 * Class:     com_robertbeckebans_tekuum_TekuumJNI
 * Method:    setLibraryDirectory
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_robertbeckebans_tekuum_TekuumJNI_setLibraryDirectory
( JNIEnv*, jclass, jstring );

/*
 * Class:     com_robertbeckebans_tekuum_TekuumJNI
 * Method:    setGameDirectory
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_robertbeckebans_tekuum_TekuumJNI_setGameDirectory
( JNIEnv*, jclass, jstring );

/*
 * Class:     com_robertbeckebans_tekuum_TekuumJNI
 * Method:    drawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_robertbeckebans_tekuum_TekuumJNI_drawFrame
( JNIEnv*, jclass );

/*
 * Class:     com_robertbeckebans_tekuum_TekuumJNI
 * Method:    queueKeyEvent
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_robertbeckebans_tekuum_TekuumJNI_queueKeyEvent
( JNIEnv*, jclass, jint, jint );

/*
 * Class:     com_robertbeckebans_tekuum_TekuumJNI
 * Method:    queueMotionEvent
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_com_robertbeckebans_tekuum_TekuumJNI_queueMotionEvent
( JNIEnv*, jclass, jint, jfloat, jfloat, jfloat );

/*
 * Class:     com_robertbeckebans_tekuum_TekuumJNI
 * Method:    queueTrackballEvent
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_com_robertbeckebans_tekuum_TekuumJNI_queueTrackballEvent
( JNIEnv*, jclass, jint, jfloat, jfloat );

/*
 * Class:     com_robertbeckebans_tekuum_TekuumJNI
 * Method:    queueJoystickEvent
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_com_robertbeckebans_tekuum_TekuumJNI_queueJoystickEvent
( JNIEnv*, jclass, jint, jfloat );

/*
 * Class:     com_robertbeckebans_tekuum_TekuumJNI
 * Method:    queueConsoleEvent
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_robertbeckebans_tekuum_TekuumJNI_queueConsoleEvent
( JNIEnv*, jclass, jstring );

/*
 * Class:     com_robertbeckebans_tekuum_TekuumJNI
 * Method:    isConsoleActive
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_robertbeckebans_tekuum_TekuumJNI_isConsoleActive
( JNIEnv*, jclass );

/*
 * Class:     com_robertbeckebans_tekuum_TekuumJNI
 * Method:    isMenuActive
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_robertbeckebans_tekuum_TekuumJNI_isMenuActive
( JNIEnv*, jclass );

#ifdef __cplusplus
}
#endif
#endif
